"""Emit data/a2zProblems.ts and data/legacyIdMap.ts from a2z.json + legacy_map.json."""
import json

J = lambda v: json.dumps(v, ensure_ascii=False)
a = json.load(open('/home/claude/a2z/a2z.json'))
STEP_NAMES = {
    1: 'Learn the Basics', 2: 'Learn Important Sorting Techniques', 3: 'Arrays [Easy -> Medium -> Hard]',
    4: 'Binary Search [1D, 2D Arrays, Search Space]', 5: 'Strings [Basic and Medium]',
    6: 'Linked List', 7: 'Recursion [PatternWise]', 8: 'Bit Manipulation', 9: 'Stack and Queues',
    10: 'Sliding Window & Two Pointer', 11: 'Heaps', 12: 'Greedy Algorithms', 13: 'Binary Trees',
    14: 'Binary Search Trees', 15: 'Graphs', 16: 'Dynamic Programming', 17: 'Tries',
    18: 'Strings [Hard]'}

def obj(p):
    parts = [f"id: {p['id']}", f"order: {p['order']}", f"step: {p['step']}",
             f"topic: {J(p['topic'])}", f"section: {J(p['section'])}", f"title: {J(p['title'])}",
             f"difficulty: {J(p['difficulty'])}"]
    if p['kind'] != 'practice': parts.append(f"kind: {J(p['kind'])}")
    plat = ', '.join(f"{k}: {J(v)}" for k, v in p['platforms'].items())
    parts.append(f"platforms: {{ {plat} }}" if plat else 'platforms: {}')
    if p.get('otherLabel'): parts.append(f"otherLabel: {J(p['otherLabel'])}")
    if p.get('article'):
        parts.append('article: { url: %s, source: %s }' % (J(p['article']['url']), J(p['article']['source'])))
    if p.get('premium'): parts.append('premium: true')
    if p.get('related'):
        rs = ', '.join('{ platform: %s, title: %s, url: %s, note: %s }' % (
            J(r['platform']), J(r['title']), J(r['url']), J(r['note'])) for r in p['related'])
        parts.append(f'related: [{rs}]')
    parts.append(f"tags: {J(p['tags'])}")
    return '  { ' + ', '.join(parts) + ' },'

lines = ['''import type { Problem } from "@/lib/types";

/**
 * Striver's A2Z DSA Sheet — complete classic 18-step roadmap (455 items), in sheet order.
 *
 * GENERATED by scripts/a2z-build (see docs/A2Z_DATASET.md for sources and the full
 * link audit). Edit by hand if you like — the app only reads this array — but keep:
 *   - `id` unique and stable (progress is stored by id),
 *   - `order` = position in the roadmap, 1..N with no gaps (run `npm run validate:data`),
 *   - `topic` equal to an id in data/topics.ts.
 *
 * Links: a platform key is present ONLY when the URL was verified to be this exact problem.
 *   leetcode — slug confirmed via LeetCode's API or by fetching the problem page
 *   gfg      — GeeksforGeeks practice page verified against its title/slug
 *   other    — TakeUForward practice page (otherLabel) or InterviewBit/HackerRank
 *   article  — an explanation to READ (TakeUForward); never used as the "Solve" link
 *   related  — suggested practice that is NOT the identical problem (never used as "Solve")
 * No Code360 links are included: none could be verified, so none are listed.
 *
 * Titles are the sheet's own titles (only spelling was corrected, e.g. "Sudoko" -> "Sudoku").
 * No problem statements are copied.
 */
export const a2zProblems: Problem[] = [''']
cur = None
for p in a:
    k = (p['step'], p['section'])
    if k != cur:
        if cur is None or cur[0] != p['step']:
            lines.append('')
            lines.append(f"  // ═══ Step {p['step']}: {STEP_NAMES[p['step']]} " + '═' * 20)
        lines.append(f"  // ── {p['section']}")
        cur = k
    lines.append(obj(p))
lines.append('];')
lines.append('')
open('/home/claude/dsa-roadmap/data/a2zProblems.ts', 'w').write('\n'.join(lines))

# ---------------------------------------------------------------- legacy map
lm = json.load(open('/home/claude/a2z/legacy_map.json'))
out = ['''/**
 * Migration map from the original 152-problem starter dataset (storage version 1) to the
 * A2Z dataset (storage version 2). Used once, automatically, by the persisted store's
 * `migrate` step and when importing an old export file.
 *
 *  - number -> the A2Z problem that is the SAME LeetCode problem (first occurrence in
 *    roadmap order). Completion date, bookmark, notes, mistakes and code move over.
 *  - null   -> no identical problem in the A2Z sheet. Nothing is deleted: that progress is
 *    kept in `legacy` storage, included in exports, and listed under Settings.
 */
export const LEGACY_ID_MAP: Record<number, number | null> = {''']
rows = sorted([(o, n, t) for o, t, n, _ in lm['mapped']] + [(o, None, t) for o, t, s, r in lm['unmapped']])
for o, n, t in rows:
    out.append(f"  {o}: {'null' if n is None else n}, // {t}")
out.append('};')
out.append('')
out.append('/** Titles of the original starter-dataset problems, for showing preserved legacy progress. */')
out.append('export const LEGACY_TITLES: Record<number, string> = {')
for o, n, t in rows:
    out.append(f'  {o}: {J(t)},')
out.append('};')
out.append('')
open('/home/claude/dsa-roadmap/data/legacyIdMap.ts', 'w').write('\n'.join(out))
print('emitted', len(a), 'problems;', len(rows), 'legacy rows')
